IniException: Class now inherits from SystemException and implements ISerializable. Message: Returns a culture-friendly line number and position with message. [Constructors]: Added several required constructors (FxCop). GetObjectData: ISerializable GetObjectData method.